Proyectofuncional/blog/api/urls.py
from django.urls import path
from blog.api.views import(
	api_detail_blog_view,
	api_update_blog_view,
	api_delete_blog_view,
	api_create_blog_view,
	ApiBlogListView,
)

app_name = 'blog'

urlpatterns = [
	path('<slug>/', api_detail_blog_view, name="detail"),
	path('<slug>/update', api_update_blog_view, name="update"),
	path('<slug>/delete', api_delete_blog_view, name="delete"),
	path('create', api_create_blog_view, name="create"),
	path('listar', ApiBlogListView.as_view(), name="listar"),
]

Proyectofuncional/blog/urls.py
from django.urls import path
from blog.views import(
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    )
app_name = 'blog'
urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
]

Proyectofuncional/proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from account.views import(
	registrarse_view,
	logout_view,
	login_view,
    account_view,
    must_authenticate_view,
    registrarse_view_api,
	)
from blog.views import(
    create_blog_view,
    home,
    comprar,
    galeriaimg,
    historiapag,
    blog,
    medio_pago,
    )
from soporte.views import(
    soporte_pag,
)

urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('', home, name=""),

    path('blog/', include('blog.urls', 'blog')),

    path('comprar/', comprar, name='comprar-pag'),

    path('medio_pago/', medio_pago, name='medio_de_pago'),
    
    path('register/',registrarse_view, name='register'),
    
    path('logout/',logout_view, name='logout'),
    
    path('login/',login_view, name='login'),
    
    path('account/',account_view, name="account"),

    path('must_authenticate/',must_authenticate_view, name="must_authenticate"),
    
    path('galeria/',galeriaimg, name="galeriaimgp"),
    
    path('historia/', historiapag, name="historiapag1"),
    
    path('blog/', blog, name="sector_blog1"),#esto puede causar un error

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='../templates/account/registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='../templates/account/registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='../templates/account/registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='../templates/account/registration/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='../templates/account/registration/password_reset_form.html'), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='../templates/account/registration/password_reset_complete.html'),
     name='password_reset_complete'),

    path('soporte/', soporte_pag, name='soporte'),

    #Sección Rest Framework
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/account/', include('account.api.urls', 'account_api')),

    #Service workers

    path('', include('pwa.urls')),

    #Sección api_registrarse

    path('register_api/',registrarse_view_api, name='register_api'),


]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyectofuncional/blog/models.py
from django.db import models


from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

def upload_location(instance, filename, **kwargs):
	file_path='blog/{author_id}/{title}-{filename}'.format(
		author_id=str(instance.author.id), title=str(instance.title), filename=filename
		)
	return file_path
class BlogPost(models.Model):
	title = models.CharField(max_length=150,null=False,blank=False)
	body = models.TextField(max_length=5000,null=False,blank=False)
	image = models.ImageField(upload_to=upload_location,null=False,blank=False)
	date_published = models.DateTimeField(auto_now_add=True,verbose_name="date published")
	date_updated = models.DateTimeField(auto_now=True,verbose_name="date updated")
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug = models.SlugField(blank=True, unique=True)
	#slug es una URL
	def __str__(self):
		return self.title
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username +"-"+ instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)


#Img gallery

class Imggal(models.Model):
	imgtitle=models.CharField(max_length=100)
	imgdesc=models.CharField(max_length=500)
	img=models.ImageField(upload_to='images/')
	def __str__(self):
		return self.imgtitle

Proyectofuncional/blog/forms.py
from django import forms
from blog.models import BlogPost


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields =['title','body','image']

class UpdateBlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields =['title','body','image']
	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title= self.cleaned_data['title']
		blog_post.body= self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']
		if commit:
			blog_post.save()
		return blog_post

Proyectofuncional/blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication


from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer

SUCCESS = 'success'
ERROR = 'error'
DELETE_SUCCESS = 'deleted'
UPDATE_SUCCESS = 'updated'
CREATE_SUCCESS = 'created'


#Obtener el blog.
@api_view(['GET', ])
@permission_classes((IsAuthenticated,))
def api_detail_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = BlogPostSerializer(blog_post)
		return Response(serializer.data)

#Actualizar el Blog
@api_view(['PUT',])
@permission_classes((IsAuthenticated,))
def api_update_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	user = request.user
	if blog_post.author != user:
		return Response({'response': "No tienes permisos para editar este blog."})

	if request.method == 'PUT':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data["success"] = "Se ha actualizado correctamente"
			return Response(data=data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#Borrar el blogpost
@api_view(['DELETE',])
@permission_classes((IsAuthenticated,))
def api_delete_blog_view(request, slug):

	try:
		blog_post = BlogPost.objects.get(slug=slug)
	except BlogPost.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)
	
	user = request.user
	if blog_post.author != user:
		return Response({'response': "No tienes permisos para Borrar este blog."})

	if request.method == 'DELETE':
		operation = blog_post.delete()
		data = {}
		if operation:
			data[SUCCESS] = DELETE_SUCCESS
		else:
			data["failure"] = "No se ha podido borrar"
		return Response(data=data)

#Crear el blog_post
@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def api_create_blog_view(request):

	account = request.user

	blog_post = BlogPost(author=account)

	if request.method == 'POST':
		serializer = BlogPostSerializer(blog_post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class ApiBlogListView(ListAPIView):
	queryset = BlogPost.objects.all()
	serializer_class = BlogPostSerializer
	authentication_classes = (TokenAuthentication,)
	permission_classes = (IsAuthenticated,)
	pagination_class= PageNumberPagination

Proyectofuncional/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from blog.models import BlogPost, Imggal
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account
from operator import attrgetter
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def home(request):
	return render(request, 'blog/inicio/index.html')
def comprar(request):
	return render(request, 'blog/comprar/comprar.html')


def historiapag(request):
	return render(request, 'blog/historia/historia.html')

BLOG_POSTS_PER_PAGE=5

def blog(request):
	context={}
	query=""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts=sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
	context['blog_posts'] = blog_posts

	#paginación

	page=request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)

	try:
		blog_posts = blog_posts_paginator.page(page)

	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)

	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render (request, 'blog/blog_sector/blog_sector.html', context)

def create_blog_view(request):

	context = {}

	user = request.user

	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()
	context['form'] = form

	return render(request, 'blog/create/create_blog.html', context)

def detail_blog_view(request, slug):
	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail/detail_blog.html', context)

def edit_blog_view(request, slug):
	context ={}

	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')
	blog_post = get_object_or_404(BlogPost, slug=slug)
	if blog_post.author != user:
		return HttpResponse("No eres el autor de esta publicación.")
	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message']="Se ha actualizado su publicación."
			blog_post = obj
	form = UpdateBlogPostForm(
		initial={
		"title": blog_post.title,
		"body": blog_post.body,
		"image": blog_post.image,
		}
	)
	context['form'] = form
	return render(request, 'blog/edit/edit_blog.html', context)

def galeriaimg(request):
	resultsdisplay=Imggal.objects.all()
	return render(request, 'blog/galeria/galeria.html',{'Imggal':resultsdisplay})

def medio_pago(request):
	return render(request, 'blog/comprar/medios_pago.html')

def get_blog_queryset(query=None):
	queryset =[]
	queries = query.split(" ") # creara una lista que dividira los términos ej:  ryzen 5600x [ryzen, 5600x], para buscarlos individualmente
	for q in queries:
		posts = BlogPost.objects.filter(
			Q(title__icontains=q)
			).distinct()
		for post in posts:
			queryset.append(post)
	return list(set(queryset))

Proyectofuncional/blog/templates/snippets/blog_post_pagination.html
<!-- Páginación Filtrada -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Anterior</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Siguiente</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Último &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>

Proyectofuncional/blog/templates/snippets/blog_post_snippet.html
{% if blog_post %}
<div class="container">
	<div class="row poppins">
		
		<!-- Blog Post -->
		<div class="card m-auto largo_card">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top redondeo-imagen" src="{{blog_post.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2 padding_card_body">
				<a class="decoraciones"href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title lightblue">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|truncatechars:250}}<a class="lightblue"href="{% url 'blog:detail' post.slug %}">Ver más.</a></p>
				<br>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary plomo color_borde_negro">Editar</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Actualizado el {{blog_post.date_updated}} por {{blog_post.author}}
			</div>
		</div>
	</div>
</div>
{% else %}
	<div class="container">
		<div class="row">
			<div class="card m-auto largo_card">
				<div class="card-body mt-2 mb-2 padding_card_body">
					<h2>Sin Resultados.</h2>
					<p>No se han encontrado resultados para: "{{query}}".</p>
				</div>
			</div>
		</div>
	</div>
{% endif %}

Proyectofuncional/blog/templates/snippets/footer.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<!-- pie de pagina -->
<footer class="aligncenter poppins">
	<div class="flexcontainer">
		<a class="flex1" href="">Acerca de Nosotros</a>
		<a class="flex1" href="">Política de privacidad</a>
		<a class="flex1" href="mailto:contactpro@aillnovo.cl">Contact us :<br>contactpro@aillnovo.cl</a>
	</div>
	<br><br>Copyright 2020 ©
</footer>

Proyectofuncional/blog/templates/snippets/header.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">